name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # This is crucial for the deployment to work.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Or your build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Use the build folder
